apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goit-argo
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: "https://github.com/SergiiGoncharov13/goit-argo.git"
    path: "/argocd/applications/mlflow"
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
