apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL:  https://repo.broadcom.com/bitnami-files
    targetRevision: 14.10.2
    chart: minio
    helm:
      values: |
        mode: standalone
        auth:
          rootUser: minioadmin
          rootPassword: minioadmin
        image:
          repository: docker.io/bitnami/minio
          tag: 2025.9.30-debian-12-r0
        defaultBuckets: "mlflow-artifacts"
        persistence:
          enabled: true
          size: 10Gi
        extraArgs:
          - server
          - /data

        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
 
  destination:
    
    server: https://kubernetes.default.svc 
    
    namespace: minio
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
