apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    chart: "minio"
    targetRevision: "14.7.16"
    helm:
      releaseName: "minio"
      values: |
        mode: standalone
        rootUser: "minio"
        rootPassword: "minio123"
        defaultBuckets: "mlflow-artifacts"
        service:
          type: ClusterIP
  destination:
    server: "https://kubernetes.default.svc"
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
