apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-postgres
  namespace: infra-tools
spec:
  destination:
    namespace: infra-tools
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 14.0.2
    helm:
      valuesObject:
        image:
          repository: docker.io/bitnamilegacy/postgresql
        auth:
          username: mlflow
          password: mlflowpass
          database: mlflow
        primary:
          persistence:
            enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true