apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-postgres
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    chart: "postgresql"
    targetRevision: "15.2.2"
    helm:
      releaseName: "mlflow-postgres"
      values: |
        auth:
          username: mlflow
          password: mlflowpass
          database: mlflow
  destination:
    server: "https://kubernetes.default.svc"
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
