apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-postgres
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 12.10.3
    helm:
      values: |
        postgresqlUsername: mlflow
        postgresqlPassword: mlflowpass
        postgresqlDatabase: mlflow
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
