apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pushgateway
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-pushgateway
    targetRevision: 1.4.0
    helm:
      values: |
        service:
          type: ClusterIP
          port: 9091
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
